# SPDX-FileCopyrightText:  © 2018, Niklas Heer <me@nheer.io>
# SPDX-FileCopyrightText: 🄯 2024, Peter J. Mello <admin@petermello.net>
#
# SPDX-License-Identifier: MIT
---
image: python:3-alpine

variables:
  DOCKER_DRIVER: overlay2

cache:
  paths:
    - .pip

before_script:
  # Print out Python version for debugging.
  - python3 -V
  - mkdir -pv .pip
  - python3 -m pip install -U pip
  - pip --cache-dir=.pip install -r requirements.txt

build:
  stage: build
  script:
    - python3 ./app.py
...
