# SPDX-FileCopyrightText: 🄯 2024, Peter J. Mello <admin@petermello.net>
#
# SPDX-License-Identifier: CC0-1.0
name: Determine code metrics

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  codecov:
    name: Codecov
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: RogueScholar/pocketcasts-stats
